import { GoogleGenAI } from "@google/genai";

// Helper to clean Base64 string (remove data URL prefix)
const cleanBase64 = (base64: string) => {
  return base64.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');
};

const RETRY_DELAY = 2000;
const MAX_RETRIES = 3;

const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

// Retry wrapper for API calls
async function retryOperation<T>(operation: () => Promise<T>): Promise<T> {
  let lastError: any;
  for (let i = 0; i < MAX_RETRIES; i++) {
    try {
      return await operation();
    } catch (error: any) {
      lastError = error;
      if (error.status === 429 || error.status === 503) {
        console.warn(`Attempt ${i + 1} failed (Quota/Service), retrying...`);
        await sleep(RETRY_DELAY * (i + 1)); // Exponential backoff
      } else {
        throw error;
      }
    }
  }
  throw lastError;
}

/**
 * FEATURE 1: Virtual Fit (Merged Workflow)
 * Uses gemini-2.5-flash-image for editing/compositing capabilities.
 */
export const generateVirtualFit = async (
  productBase64: string,
  modelBase64: string,
  apiKey: string
): Promise<string> => {
  if (!apiKey) throw new Error("API Key is missing");

  const ai = new GoogleGenAI({ apiKey });

  const prompt = `
    You are an expert fashion compositor and photo editor.
    Image 1 is a garment product shot.
    Image 2 is a human model.
    Task: Realistically dress the model in Image 2 with the garment from Image 1.
    - Adjust the fit to match the model's pose and body shape seamlessly.
    - Preserve the model's skin tone, lighting, and shadows.
    - Ensure natural fabric folds and drape physics.
    - Return ONLY the final composited image.
  `;

  return retryOperation(async () => {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          { text: prompt },
          {
            inlineData: {
              mimeType: 'image/png',
              data: cleanBase64(productBase64)
            }
          },
          {
            inlineData: {
              mimeType: 'image/png',
              data: cleanBase64(modelBase64)
            }
          }
        ]
      },
      config: {
        // No system instruction for vision models in some contexts, keeping it in prompt
      }
    });

    // Extract image
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData && part.inlineData.data) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    throw new Error("No image generated by Virtual Fit model.");
  });
};

/**
 * FEATURE 2: Scene Magic (Background Replacement)
 */
export const generateSceneMagic = async (
  imageBase64: string,
  scenePrompt: string,
  apiKey: string
): Promise<string> => {
  if (!apiKey) throw new Error("API Key is missing");
  const ai = new GoogleGenAI({ apiKey });

  const fullPrompt = `
    Edit this fashion image. Replace the background with: ${scenePrompt}.
    Keep the model and clothing exactly as they are.
    Ensure the lighting on the model matches the new environment.
    High fashion photography style, 4k, photorealistic.
  `;

  return retryOperation(async () => {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image', // Good for editing
      contents: {
        parts: [
          { text: fullPrompt },
          {
            inlineData: {
              mimeType: 'image/png',
              data: cleanBase64(imageBase64)
            }
          }
        ]
      }
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData && part.inlineData.data) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    throw new Error("No image generated for Scene Magic.");
  });
};

/**
 * FEATURE 3: Cinematic Video (Veo)
 */
export const generateCinematicVideo = async (
  prompt: string,
  apiKey: string,
  imageBase64?: string
): Promise<string> => {
  if (!apiKey) throw new Error("API Key is missing");
  const ai = new GoogleGenAI({ apiKey });

  // Start Operation
  let operation = await retryOperation(async () => {
    return await ai.models.generateVideos({
      model: 'veo-3.1-fast-generate-preview', // Fast preview for better UX
      prompt: prompt,
      ...(imageBase64 && {
        image: {
          imageBytes: cleanBase64(imageBase64),
          mimeType: 'image/png'
        }
      }),
      config: {
        numberOfVideos: 1,
        resolution: '720p',
        aspectRatio: '9:16' // Mobile first video
      }
    });
  });

  // Poll for completion
  console.log("Video generation started...", operation);
  
  while (!operation.done) {
    await sleep(5000); // Wait 5 seconds between checks
    console.log("Polling video status...");
    operation = await ai.operations.getVideosOperation({ operation: operation });
  }

  const downloadUri = operation.response?.generatedVideos?.[0]?.video?.uri;
  
  if (!downloadUri) {
    throw new Error("Video generation failed or returned no URI.");
  }

  // Fetch the actual video bytes using the API Key
  const videoResponse = await fetch(`${downloadUri}&key=${apiKey}`);
  if (!videoResponse.ok) {
     throw new Error(`Failed to download video: ${videoResponse.statusText}`);
  }
  
  const blob = await videoResponse.blob();
  return URL.createObjectURL(blob);
};
